[package]
name = "shimmer"
version = "0.1.0"
edition = "2021"

[lib]
name = "shimmer"
path = "src/lib.rs"

[[bin]]
name = "shimmer"
path = "src/main.rs"

[dependencies]
glam = "0.22.0"
palette = "0.6.1"
rand = "0.8.5"
